#!/bin/bash
# Pull okadmin secrets from GCP Secret Manager (project starful-258005).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT="${GCP_PROJECT_ID:-starful-258005}"
SECRETS_DIR="$ROOT/secrets"
ENV_FILE="$ROOT/.env"

mkdir -p "$SECRETS_DIR"
gcloud secrets versions access latest --secret=starfu-biz-firebase --project="$PROJECT" \
  >"$SECRETS_DIR/firebase-key.json"
chmod 600 "$SECRETS_DIR/firebase-key.json"

PLACES="$(gcloud secrets versions access latest --secret=GOOGLE_PLACES_API_KEY --project="$PROJECT")"
OAUTH_ID="$(gcloud secrets versions access latest --secret=OKADMIN_GOOGLE_OAUTH_CLIENT_ID --project="$PROJECT")"
OAUTH_SECRET="$(gcloud secrets versions access latest --secret=OKADMIN_GOOGLE_OAUTH_CLIENT_SECRET --project="$PROJECT")"
FLASK_SK="$(gcloud secrets versions access latest --secret=OKADMIN_FLASK_SECRET_KEY --project="$PROJECT")"
GEMINI="$(gcloud secrets versions access latest --secret=GEMINI_API_KEY --project="$PROJECT" 2>/dev/null || true)"
KRCAMPUS_MAPS="$(gcloud secrets versions access latest --secret=KRCAMPUS_GOOGLE_MAPS_API_KEY --project="$PROJECT" 2>/dev/null || true)"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/fetch_secrets.sh — do not commit
WORK_ROOT=/opt/work
SITES_YAML=/opt/work/sites.yaml
PORT=8090

GOOGLE_APPLICATION_CREDENTIALS=secrets/firebase-key.json
GOOGLE_PLACES_API_KEY=${PLACES}

GOOGLE_OAUTH_CLIENT_ID=${OAUTH_ID}
GOOGLE_OAUTH_CLIENT_SECRET=${OAUTH_SECRET}
FLASK_SECRET_KEY=${FLASK_SK}
ALLOWED_EMAILS=your@email.com
LOCAL_DEV_AUTH=1
DEV_LOGIN_EMAIL=your@email.com

GEMINI_API_KEY=${GEMINI}
GEMINI_MODEL=gemini-flash-latest
KRCAMPUS_GOOGLE_MAPS_API_KEY=${KRCAMPUS_MAPS}
EOF
chmod 600 "$ENV_FILE"
if [ -n "$KRCAMPUS_MAPS" ] && [ -f "/opt/work/krcampus/.env" ]; then
  if grep -q '^KRCAMPUS_GOOGLE_MAPS_API_KEY=' /opt/work/krcampus/.env; then
    sed -i.bak "s|^KRCAMPUS_GOOGLE_MAPS_API_KEY=.*|KRCAMPUS_GOOGLE_MAPS_API_KEY=\"${KRCAMPUS_MAPS}\"|" /opt/work/krcampus/.env
    rm -f /opt/work/krcampus/.env.bak
  else
    printf '\nKRCAMPUS_GOOGLE_MAPS_API_KEY="%s"\n' "$KRCAMPUS_MAPS" >> /opt/work/krcampus/.env
  fi
fi
echo "OK: $SECRETS_DIR/firebase-key.json and $ENV_FILE"
